trigger:
  - main
stages:
  - stage: Build
    displayName: Build Package
    jobs:
    - job: BuildPackage
      pool: uiPool
      variables:
        version: '$[counter(1,1)]'
        process: '$currUAT'

      steps:
      - task: UiPathPack@2
        inputs:
          versionType: 'ManualVersion'
          version: '1.$(version)'
          projectJsonPath: 'project.json'
          outputType: 'Process'
          orchestratorConnection: '8DEv1AMNXczW3y4U15LL3jYf62jK93n5'
          outputPath: '$(Build.ArtifactStagingDirectory)\Output'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: CurrencyArtifact


  - stage: DeployUAT
    displayName: Deploy build artifact to UAT
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: deployDEV
        displayName: Deploy package to TEST Orchestrator
        pool: uiPool
        environment: UAT
        strategy:
         runOnce:
          deploy:
           steps:
            - task: UiPathDeploy@2
              inputs:
                orchestratorConnection: '8DEv1AMNXczW3y4U15LL3jYf62jK93n5'
                packagesPath: '$(System.DefaultWorkingDirectory)\Output\'
                folderName: 'Workspace'
                environments: 'UAT'

  - stage: DeployPROD
    displayName: Deploy build artifact to PROD
    dependsOn: DeployUAT
    condition: succeeded()
    
    jobs:
      - deployment: deployDEV
        displayName: Deploy package to PROD Orchestrator
        pool: uiPool
        environment: PROD
        strategy:
         runOnce:
          deploy:
           steps:
            - task: UiPathDeploy@2
              inputs:
                orchestratorConnection: '8DEv1AMNXczW3y4U15LL3jYf62jK93n5'
                packagesPath: '$(Pipeline.Workspace)\CurrencyArtifact\'
                folderName: 'Workspace'
                environments: 'PROD'
